filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/apache2/access.log
    tags: [ "1001" ]

  - type: log
    enabled: true
    paths:
      - /var/log/apache2/error.log
    tags: [ "1002" ]

output.logstash:
  hosts: ["ls01-shipper:5044"]
  loadbalance: true