heartbeat.monitors:
  - type: icmp
    enabled: true
    schedule: '@every 60s'
    hosts:
      - wp.pl
    wait: 1s
    ipv6: false
    tags: [ "1001" ]

  - type: http
    enabled: true
    schedule: '@every 60s'
    hosts:
      - http://wp.pl
    timeout: 3s
    check.request:
      method: GET
    tags: [ "1002" ]

output.logstash:
  hosts: ["ls01-shipper:5044"]
  loadbalance: true